version: '2'
services:
  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    hostname: node-exporter
    ports:
     - "9100:9100"
    network_mode: host
