---
- hosts: prometheus
  remote_user: root
  vars_files:
    - ../conf/monitor_vars.yml
    - ../conf/setup_vars.yml
  tasks:
  - name: mkdir dest path
    file:
      path: "{{ prometheus_dest_path }}"
      state: directory

  - name: cp docker compose yaml to dest
    copy:
      src: "{{ starrocks_ansible_home}}/files/prometheus"
      dest: "{{ prometheus_dest_path }}/"

  - name: start docker yaml
    shell: docker-compose -f "{{ prometheus_dest_path }}/prometheus/docker-compose.yaml" up -d

  - name: alter prometheus conf
    replace:
        path: "{{ prometheus_dest_path }}/prometheus/prometheus.yml"
        regexp: "\"fefefe\""
        replace: "{{ fe }}"

  - name: alter prometheus conf
    replace:
        path: "{{ prometheus_dest_path }}/prometheus/prometheus.yml"
        regexp: "\"bebebe\""
        replace: "{{ be }}"

  - name: alter prometheus conf
    replace:
        path: "{{ prometheus_dest_path }}/prometheus/prometheus.yml"
        regexp: "linux1:9093"
        replace: "{{ alertmanager }}"

  - name: alter prometheus conf
    replace:
        path: "{{ prometheus_dest_path }}/prometheus/prometheus.yml"
        regexp: "\"diskdiskdisk\""
        replace: "{{ node_exporter }}"
  - name: alter prometheus conf
    replace:
        path: "{{ prometheus_dest_path }}/prometheus/prometheus.yml"
        regexp: "\"linux1:9091\""
        replace: "{{ pushgateway }}"

- name: get docker id
    shell: docker ps -a |grep prometheus |awk -F '  '  '{print $1}'
    register: docker
    ignore_errors: true

  - name: cp conf to docker
    shell:
      cmd: |
        docker cp {{ prometheus_dest_path }}/prometheus/prometheus.yml {{ docker.stdout }}:/etc/prometheus/
        docker cp {{ prometheus_dest_path }}/prometheus/rules {{ docker.stdout }}:/etc/prometheus/
        docker-compose -f "{{ prometheus_dest_path }}/prometheus/docker-compose.yaml" restart
