---
- hosts: "{{ cluster }}.sr_hosts"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
  - name: decompress all SR Software packages
    unarchive:
      src: "{{ sr_filepath }}"
      dest: "{{ dest_filepath }}"
      copy: yes
  - name: mkdir meta 
    file: 
      path: "{{ metadata_path }}"
      state: directory
  - name: mkdir storage
    file: 
      path: "{{ item | regex_replace(',medium:HDD') | regex_replace(',medium:SSD') }}"
      state: directory
    with_items: "{{storage_root_path.split(';')}}"
  - name: export java home for start_fe
    lineinfile: 
      path: "{{ sr_home }}/fe/bin/start_fe.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home }}"

  - name: export java home for broker
    lineinfile:
      path: "{{ sr_home }}/apache_hdfs_broker/bin/start_broker.sh"
      insertafter: "# java"
      line: "export JAVA_HOME={{ java_home }}"

- hosts: "{{ cluster }}.master"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: alter fe_priority_networks
      lineinfile:
        dest: "{{ sr_home }}/fe/conf/fe.conf"
        insertafter: "# priority_networks"
        line: "priority_networks = {{ be_priority_networks }}\n"
    - name: alter fe http_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "8030"
        replace: "{{ http_port }}"
    - name: alter fe rpc_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9020"
        replace: "{{ rpc_port }}"
    - name: alter fe query_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9030"
        replace: "{{ query_port }}"
    - name: alter fe edit_log_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9010"
        replace: "{{ edit_log_port }}"
    - name: alter fe metadata_dir
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9010"
        replace: "{{ edit_log_port }}"
    - name: alter fe metadir
      lineinfile:
        dest: "{{ sr_home }}/fe/conf/fe.conf"
        insertafter: "# store metadata"
        line: "meta_dir = {{ metadata_path }}\n"
    - name: scp fe.conf
      copy:
        src: "{{ fe_conf_path }}"
        dest: "{{ sr_home }}/fe/conf/"
        force: yes
    - name: start master
      shell:
        cmd:
          sh {{ sr_home }}/fe/bin/start_fe.sh --daemon

- hosts: "{{ cluster }}.follower"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: alter fe_priority_networks
      lineinfile:
        dest: "{{ sr_home }}/fe/conf/fe.conf"
        insertafter: "# priority_networks"
        line: "priority_networks = {{ fe_priority_networks }}\n"
    - name: alter fe http_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "8030"
        replace: "{{ http_port }}"
    - name: alter fe rpc_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9020"
        replace: "{{ rpc_port }}"
    - name: alter fe query_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9030"
        replace: "{{ query_port }}"
    - name: alter fe edit_log_port
      replace:
        path: "{{ sr_home }}/fe/conf/fe.conf"
        regexp: "9010"
        replace: "{{ edit_log_port }}"
    - name: alter fe metadir
      lineinfile:
        dest: "{{ sr_home }}/fe/conf/fe.conf"
        insertafter: "# store metadata"
        line: "meta_dir = {{ metadata_path }}\n"
    - name: scp fe.conf
      copy:
        src: "{{ fe_conf_path }}"
        dest: "{{ sr_home }}/fe/conf/"
        force: yes
    - name: start follower
      shell:
        cmd: "sh {{ sr_home }}/fe/bin/start_fe.sh --helper {{ master }}:{{ edit_log_port }} --daemon"

- hosts: "{{ cluster }}.backends"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
    - ../conf/{{ cluster }}.yml
  tasks:
    - name: alter be_priority_networks
      lineinfile:
        dest: "{{ sr_home }}/be/conf/be.conf"
        insertafter: "# priority_networks"
        line: "priority_networks = {{ be_priority_networks }}\n"
    - name: alter be be_port
      replace:
        path: "{{ sr_home }}/be/conf/be.conf"
        regexp: "9060"
        replace: "{{ be_port }}"
    - name: alter be webserver_port
      replace:
        path: "{{ sr_home }}/be/conf/be.conf"
        regexp: "8040"
        replace: "{{ webserver_port }}"
    - name: alter be heartbeat_service_port
      replace:
        path: "{{ sr_home }}/be/conf/be.conf"
        regexp: "9050"
        replace: "{{ heartbeat_service_port }}"
    - name: alter be brpc_port
      replace:
        path: "{{ sr_home }}/be/conf/be.conf"
        regexp: "8060"
        replace: "{{ brpc_port }}"
    - name: alter be metadir
      lineinfile:
        dest: "{{ sr_home }}/be/conf/be.conf"
        insertafter: "# storage_root_path"
        line: "storage_root_path = {{ storage_root_path }}\n"
    - name: scp be.conf
      copy:
        src: "{{ be_conf_path }}"
        dest: "{{ sr_home }}/be/conf/"
        force: yes
    - name: start all backends
      shell:
        cmd: "sh {{ sr_home }}/be/bin/start_be.sh --daemon"

- hosts: "{{ cluster }}.brokers"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: start all brokers
      shell:
        cmd: "sh {{ sr_home }}/apache_hdfs_broker/bin/start_broker.sh --daemon"
