---
- hosts: "{{ cluster }}.brokers"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: stop all brokers
      shell:
        cmd: "sh {{ sr_home }}/apache_hdfs_broker/bin/stop_broker.sh"
- hosts: "{{ cluster }}.backends"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: stop all backends
      shell:
        cmd: "sh {{ sr_home }}/be/bin/stop_be.sh"
- hosts: "{{ cluster }}.follower"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: stop all follower
      shell:
        cmd: "sh {{ sr_home }}/fe/bin/stop_fe.sh"
- hosts: "{{ cluster }}.master"
  remote_user: root
  vars_files:
    - ../conf/setup_vars.yml
  tasks:
    - name: stop master
      shell:
        cmd: "sh {{ sr_home }}/fe/bin/stop_fe.sh"
