---
- hosts: "{{ cluster }}.sr_hosts"
  remote_user: root
  vars_files:
    - ../conf/upgrade_vars.yml
  tasks:
    - name:  decompress new SR Software packages
      unarchive:
        src: "{{ newsr_filepath }}"
        dest: "{{ newsr_destpath }}"
        copy: yes

    - name: export java home for start_fe
      lineinfile: 
        path: "{{ newsr_home }}/fe/bin/start_fe.sh"
        insertafter: "# java"
        line: "export JAVA_HOME={{ java_home }}"
    - name: export java home for broker
      lineinfile:
        path: "{{ newsr_home }}/apache_hdfs_broker/bin/start_broker.sh"
        insertafter: "# java"
        line: "export JAVA_HOME={{ java_home }}"

- hosts: "{{ cluster }}.backends"
  remote_user: root
  vars_files:
    - ../conf/upgrade_vars.yml
    - ../conf/setup_vars.yml
  tasks:
    - name: update backends
      shell:
        cmd: 
          mv {{ newsr_home }}/be/conf/be.conf {{ newsr_home }}/be/conf/new_be.conf &&
          sh {{ sr_home }}/be/bin/stop_be.sh &&
          cp -r {{ newsr_home }}/be {{ sr_home }}/be/../ && 
          sh {{ sr_home }}/be/bin/start_be.sh --daemon
- hosts: "{{ cluster }}.brokers"
  remote_user: root
  vars_files:
    - ../conf/upgrade_vars.yml
    - ../conf/setup_vars.yml
  tasks:
    - name: update brokers
      shell: 
        cmd: 
          mv {{ newsr_home }}/apache_hdfs_broker/conf/apache_hdfs_broker.conf {{ newsr_home }}/apache_hdfs_broker/conf/new_apache_hdfs_broker.conf &&
          sh {{ sr_home }}/apache_hdfs_broker/bin/stop_broker.sh &&
          cp -r {{ newsr_home }}/apache_hdfs_broker {{ sr_home }}/apache_hdfs_broker/../ &&
          sh {{ sr_home }}/apache_hdfs_broker/bin/start_broker.sh --daemon 
- hosts: "{{ cluster }}.follower"
  remote_user: root
  vars_files:
    - ../conf/upgrade_vars.yml
    - ../conf/setup_vars.yml
  tasks:
    - name:
      shell:
        cmd:  
          mv {{ newsr_home }}/fe/conf/fe.conf {{ newsr_home }}/fe/conf/new_fe.conf &&
          sh {{ sr_home }}/fe/bin/stop_fe.sh &&
          cp -r {{ newsr_home }}/fe {{ sr_home }}/fe/../ &&
          sh {{ sr_home }}/fe/bin/start_fe.sh --daemon
- hosts: "{{ cluster }}.master"
  remote_user: root
  vars_files:
    - ../conf/upgrade_vars.yml
    - ../conf/setup_vars.yml
  tasks:
    - name:
      shell:
        cmd: 
          mv {{ newsr_home }}/fe/conf/fe.conf {{ newsr_home }}/fe/conf/new_fe.conf &&
          sh {{ sr_home }}/fe/bin/stop_fe.sh &&
          cp -r {{ newsr_home }}/fe {{ sr_home }}/fe/../ &&
          sh {{ sr_home }}/fe/bin/start_fe.sh --daemon 
